// Mock data — shape must stay identical to the real backend contract.
// Do not rename fields; teammates' code (and the live backend swap) depends on this shape.

export const MOCK_ASSETS = [
  // ── Gujarat assets ──────────────────────────────────────────────────────────
  {
    asset_id: 'FD-268',
    location: { lat: 23.24, lon: 69.67, name: 'Kutch Feeder 8', state: 'Gujarat', district: 'Kutch' },
    asset_type: 'feeder',
    risk_score: 0.91,
    risk_level: 'high',
    contributing_factors: [
      { factor: 'load_overcurrent', value: 'sustained_peak', weight: 0.5 },
      { factor: 'weather_forecast', value: 'heat_wave', weight: 0.3 },
      { factor: 'age', value: '24_years', weight: 0.2 },
    ],
    predicted_days_to_failure: 6,
    customers_affected_estimate: 3800,
    sensor: { temperature_c: 87, vibration_mm_s: 4.1, oil_bdv_kv: 18, partial_discharge_pc: 320 },
    weather: { condition: 'Heat Wave', wind_kmh: 45, humidity_pct: 22, rain_mm: 0 },
  },
  {
    asset_id: 'TX-104',
    location: { lat: 22.56, lon: 72.93, name: 'Anand Substation 4', state: 'Gujarat', district: 'Anand' },
    asset_type: 'transformer',
    risk_score: 0.87,
    risk_level: 'high',
    contributing_factors: [
      { factor: 'oil_quality', value: 'degraded', weight: 0.4 },
      { factor: 'vibration', value: 'above_threshold', weight: 0.3 },
      { factor: 'weather_forecast', value: 'storm_72h', weight: 0.3 },
    ],
    predicted_days_to_failure: 9,
    customers_affected_estimate: 4200,
    sensor: { temperature_c: 82, vibration_mm_s: 3.7, oil_bdv_kv: 22, partial_discharge_pc: 280 },
    weather: { condition: 'Storm Warning', wind_kmh: 68, humidity_pct: 78, rain_mm: 22 },
  },
  {
    asset_id: 'TX-330',
    location: { lat: 22.3, lon: 70.8, name: 'Rajkot Substation 2', state: 'Gujarat', district: 'Rajkot' },
    asset_type: 'transformer',
    risk_score: 0.82,
    risk_level: 'high',
    contributing_factors: [
      { factor: 'weather_forecast', value: 'storm_72h', weight: 0.4 },
      { factor: 'oil_quality', value: 'degraded', weight: 0.35 },
      { factor: 'vibration', value: 'above_threshold', weight: 0.25 },
    ],
    predicted_days_to_failure: 10,
    customers_affected_estimate: 4700,
    sensor: { temperature_c: 79, vibration_mm_s: 3.2, oil_bdv_kv: 24, partial_discharge_pc: 240 },
    weather: { condition: 'Unplanned Outage', wind_kmh: 55, humidity_pct: 72, rain_mm: 18 },
  },
  {
    asset_id: 'FD-221',
    location: { lat: 23.03, lon: 72.58, name: 'Naranpura Feeder 2', state: 'Gujarat', district: 'Ahmedabad' },
    asset_type: 'feeder',
    risk_score: 0.79,
    risk_level: 'high',
    contributing_factors: [
      { factor: 'load_overcurrent', value: 'sustained_peak', weight: 0.45 },
      { factor: 'age', value: '28_years', weight: 0.25 },
      { factor: 'weather_forecast', value: 'heat_wave', weight: 0.3 },
    ],
    predicted_days_to_failure: 14,
    customers_affected_estimate: 6800,
    sensor: { temperature_c: 76, vibration_mm_s: 2.9, oil_bdv_kv: 28, partial_discharge_pc: 195 },
    weather: { condition: 'Heat Wave', wind_kmh: 38, humidity_pct: 35, rain_mm: 0 },
  },
  {
    asset_id: 'TX-088',
    location: { lat: 21.17, lon: 72.83, name: 'Surat East Substation', state: 'Gujarat', district: 'Surat' },
    asset_type: 'transformer',
    risk_score: 0.78,
    risk_level: 'high',
    contributing_factors: [
      { factor: 'oil_quality', value: 'moderate', weight: 0.3 },
      { factor: 'maintenance_overdue', value: '46_days', weight: 0.4 },
      { factor: 'weather_forecast', value: 'storm_72h', weight: 0.3 },
    ],
    predicted_days_to_failure: 12,
    customers_affected_estimate: 3100,
    sensor: { temperature_c: 74, vibration_mm_s: 2.5, oil_bdv_kv: 30, partial_discharge_pc: 168 },
    weather: { condition: 'Storm Approaching', wind_kmh: 62, humidity_pct: 82, rain_mm: 14 },
  },
  {
    asset_id: 'FD-146',
    location: { lat: 21.7, lon: 72.46, name: 'Bharuch Feeder 1', state: 'Gujarat', district: 'Bharuch' },
    asset_type: 'feeder',
    risk_score: 0.71,
    risk_level: 'high',
    contributing_factors: [
      { factor: 'load_overcurrent', value: 'peak_exceeded', weight: 0.4 },
      { factor: 'vegetation_contact_risk', value: 'elevated', weight: 0.3 },
      { factor: 'weather_forecast', value: 'storm_72h', weight: 0.3 },
    ],
    predicted_days_to_failure: 11,
    customers_affected_estimate: 5300,
    sensor: { temperature_c: 71, vibration_mm_s: 2.1, oil_bdv_kv: 34, partial_discharge_pc: 145 },
    weather: { condition: 'Storm Warning', wind_kmh: 58, humidity_pct: 75, rain_mm: 12 },
  },
  {
    asset_id: 'TX-501',
    location: { lat: 21.52, lon: 70.46, name: 'Junagadh Substation 1', state: 'Gujarat', district: 'Junagadh' },
    asset_type: 'transformer',
    risk_score: 0.63,
    risk_level: 'medium',
    contributing_factors: [
      { factor: 'weather_forecast', value: 'monsoon_humidity', weight: 0.4 },
      { factor: 'oil_quality', value: 'moderate', weight: 0.35 },
      { factor: 'age', value: '18_years', weight: 0.25 },
    ],
    predicted_days_to_failure: 22,
    customers_affected_estimate: 2800,
    sensor: { temperature_c: 68, vibration_mm_s: 1.8, oil_bdv_kv: 38, partial_discharge_pc: 120 },
    weather: { condition: 'Monsoon', wind_kmh: 42, humidity_pct: 88, rain_mm: 28 },
  },
  {
    asset_id: 'BR-317',
    location: { lat: 22.31, lon: 73.19, name: 'Vadodara Ring Breaker 3', state: 'Gujarat', district: 'Vadodara' },
    asset_type: 'breaker',
    risk_score: 0.58,
    risk_level: 'medium',
    contributing_factors: [
      { factor: 'switch_cycle_count', value: 'high', weight: 0.35 },
      { factor: 'corrosion', value: 'visible', weight: 0.35 },
      { factor: 'weather_forecast', value: 'monsoon_humidity', weight: 0.2 },
    ],
    predicted_days_to_failure: 31,
    customers_affected_estimate: 2450,
    sensor: { temperature_c: 62, vibration_mm_s: 1.5, oil_bdv_kv: 42, partial_discharge_pc: 95 },
    weather: { condition: 'Monsoon', wind_kmh: 38, humidity_pct: 84, rain_mm: 18 },
  },
  {
    asset_id: 'FD-602',
    location: { lat: 23.59, lon: 72.97, name: 'Mehsana Feeder 3', state: 'Gujarat', district: 'Mehsana' },
    asset_type: 'feeder',
    risk_score: 0.55,
    risk_level: 'medium',
    contributing_factors: [
      { factor: 'load_overcurrent', value: 'moderate', weight: 0.4 },
      { factor: 'age', value: '15_years', weight: 0.3 },
      { factor: 'weather_forecast', value: 'heat_wave', weight: 0.3 },
    ],
    predicted_days_to_failure: 35,
    customers_affected_estimate: 1900,
    sensor: { temperature_c: 58, vibration_mm_s: 1.3, oil_bdv_kv: 45, partial_discharge_pc: 88 },
    weather: { condition: 'Heat Wave', wind_kmh: 32, humidity_pct: 28, rain_mm: 0 },
  },
  {
    asset_id: 'TX-410',
    location: { lat: 21.76, lon: 71.97, name: 'Bhavnagar Substation 2', state: 'Gujarat', district: 'Bhavnagar' },
    asset_type: 'transformer',
    risk_score: 0.52,
    risk_level: 'medium',
    contributing_factors: [
      { factor: 'oil_quality', value: 'moderate', weight: 0.35 },
      { factor: 'maintenance_overdue', value: '28_days', weight: 0.3 },
      { factor: 'weather_forecast', value: 'monsoon_humidity', weight: 0.35 },
    ],
    predicted_days_to_failure: 38,
    customers_affected_estimate: 2200,
    sensor: { temperature_c: 56, vibration_mm_s: 1.2, oil_bdv_kv: 46, partial_discharge_pc: 80 },
    weather: { condition: 'Monsoon', wind_kmh: 35, humidity_pct: 86, rain_mm: 22 },
  },
  {
    asset_id: 'FD-712',
    location: { lat: 24.18, lon: 72.43, name: 'Banaskantha Feeder 5', state: 'Gujarat', district: 'Banaskantha' },
    asset_type: 'feeder',
    risk_score: 0.48,
    risk_level: 'medium',
    contributing_factors: [
      { factor: 'age', value: '16_years', weight: 0.35 },
      { factor: 'load_overcurrent', value: 'moderate', weight: 0.35 },
      { factor: 'weather_forecast', value: 'dust_storm', weight: 0.3 },
    ],
    predicted_days_to_failure: 42,
    customers_affected_estimate: 1600,
    sensor: { temperature_c: 54, vibration_mm_s: 1.1, oil_bdv_kv: 48, partial_discharge_pc: 72 },
    weather: { condition: 'Dust Storm', wind_kmh: 52, humidity_pct: 18, rain_mm: 0 },
  },
  {
    asset_id: 'TX-620',
    location: { lat: 23.84, lon: 72.1, name: 'Patan Substation 1', state: 'Gujarat', district: 'Patan' },
    asset_type: 'transformer',
    risk_score: 0.45,
    risk_level: 'medium',
    contributing_factors: [
      { factor: 'oil_quality', value: 'moderate', weight: 0.3 },
      { factor: 'age', value: '14_years', weight: 0.3 },
      { factor: 'weather_forecast', value: 'dust_storm', weight: 0.4 },
    ],
    predicted_days_to_failure: 45,
    customers_affected_estimate: 1400,
    sensor: { temperature_c: 52, vibration_mm_s: 1.0, oil_bdv_kv: 50, partial_discharge_pc: 65 },
    weather: { condition: 'Dust Storm', wind_kmh: 48, humidity_pct: 20, rain_mm: 0 },
  },
  {
    asset_id: 'TX-720',
    location: { lat: 23.22, lon: 72.65, name: 'Gandhinagar Substation', state: 'Gujarat', district: 'Gandhinagar' },
    asset_type: 'transformer',
    risk_score: 0.42,
    risk_level: 'medium',
    contributing_factors: [
      { factor: 'maintenance_overdue', value: '21_days', weight: 0.4 },
      { factor: 'age', value: '12_years', weight: 0.3 },
      { factor: 'weather_forecast', value: 'heat_wave', weight: 0.3 },
    ],
    predicted_days_to_failure: 48,
    customers_affected_estimate: 2100,
    sensor: { temperature_c: 50, vibration_mm_s: 0.9, oil_bdv_kv: 52, partial_discharge_pc: 58 },
    weather: { condition: 'Heat Wave', wind_kmh: 30, humidity_pct: 30, rain_mm: 0 },
  },
  {
    asset_id: 'TX-810',
    location: { lat: 22.47, lon: 70.06, name: 'Jamnagar Substation 1', state: 'Gujarat', district: 'Jamnagar' },
    asset_type: 'transformer',
    risk_score: 0.41,
    risk_level: 'medium',
    contributing_factors: [
      { factor: 'corrosion', value: 'salt_exposure', weight: 0.4 },
      { factor: 'oil_quality', value: 'moderate', weight: 0.3 },
      { factor: 'weather_forecast', value: 'monsoon_humidity', weight: 0.3 },
    ],
    predicted_days_to_failure: 50,
    customers_affected_estimate: 2000,
    sensor: { temperature_c: 49, vibration_mm_s: 0.9, oil_bdv_kv: 53, partial_discharge_pc: 55 },
    weather: { condition: 'Monsoon', wind_kmh: 40, humidity_pct: 90, rain_mm: 32 },
  },
  {
    asset_id: 'FD-900',
    location: { lat: 20.95, lon: 72.94, name: 'Navsari Feeder 2', state: 'Gujarat', district: 'Navsari' },
    asset_type: 'feeder',
    risk_score: 0.38,
    risk_level: 'medium',
    contributing_factors: [
      { factor: 'vegetation_contact_risk', value: 'moderate', weight: 0.4 },
      { factor: 'age', value: '12_years', weight: 0.3 },
      { factor: 'weather_forecast', value: 'monsoon_humidity', weight: 0.3 },
    ],
    predicted_days_to_failure: 55,
    customers_affected_estimate: 1200,
    sensor: { temperature_c: 46, vibration_mm_s: 0.8, oil_bdv_kv: 55, partial_discharge_pc: 48 },
    weather: { condition: 'Monsoon', wind_kmh: 36, humidity_pct: 88, rain_mm: 26 },
  },
  {
    asset_id: 'PL-542',
    location: { lat: 22.99, lon: 72.5, name: 'Gandhinagar Pole Line 5', state: 'Gujarat', district: 'Gandhinagar' },
    asset_type: 'pole',
    risk_score: 0.34,
    risk_level: 'low',
    contributing_factors: [
      { factor: 'wood_decay_index', value: 'low', weight: 0.5 },
      { factor: 'lean_angle', value: 'within_spec', weight: 0.2 },
      { factor: 'weather_forecast', value: 'clear', weight: 0.1 },
    ],
    predicted_days_to_failure: 96,
    customers_affected_estimate: 640,
    sensor: { temperature_c: 42, vibration_mm_s: 0.5, oil_bdv_kv: 62, partial_discharge_pc: 28 },
    weather: { condition: 'Clear', wind_kmh: 18, humidity_pct: 45, rain_mm: 0 },
  },
  {
    asset_id: 'TX-019',
    location: { lat: 23.0, lon: 72.5, name: 'Ahmedabad North Substation', state: 'Gujarat', district: 'Ahmedabad' },
    asset_type: 'transformer',
    risk_score: 0.22,
    risk_level: 'low',
    contributing_factors: [
      { factor: 'oil_quality', value: 'good', weight: 0.4 },
      { factor: 'vibration', value: 'nominal', weight: 0.3 },
      { factor: 'maintenance_overdue', value: 'none', weight: 0.1 },
    ],
    predicted_days_to_failure: 140,
    customers_affected_estimate: 5100,
    sensor: { temperature_c: 38, vibration_mm_s: 0.4, oil_bdv_kv: 68, partial_discharge_pc: 18 },
    weather: { condition: 'Clear', wind_kmh: 15, humidity_pct: 42, rain_mm: 0 },
  },
  {
    asset_id: 'TX-560',
    location: { lat: 23.0, lon: 73.7, name: 'Sabarkantha Substation', state: 'Gujarat', district: 'Sabarkantha' },
    asset_type: 'transformer',
    risk_score: 0.28,
    risk_level: 'low',
    contributing_factors: [
      { factor: 'oil_quality', value: 'good', weight: 0.4 },
      { factor: 'age', value: '8_years', weight: 0.2 },
      { factor: 'weather_forecast', value: 'clear', weight: 0.1 },
    ],
    predicted_days_to_failure: 120,
    customers_affected_estimate: 1800,
    sensor: { temperature_c: 40, vibration_mm_s: 0.5, oil_bdv_kv: 65, partial_discharge_pc: 22 },
    weather: { condition: 'Clear', wind_kmh: 20, humidity_pct: 48, rain_mm: 0 },
  },
  {
    asset_id: 'FD-305',
    location: { lat: 22.01, lon: 73.0, name: 'Narmada Feeder 1', state: 'Gujarat', district: 'Narmada' },
    asset_type: 'feeder',
    risk_score: 0.31,
    risk_level: 'low',
    contributing_factors: [
      { factor: 'load_overcurrent', value: 'nominal', weight: 0.3 },
      { factor: 'age', value: '7_years', weight: 0.2 },
      { factor: 'weather_forecast', value: 'clear', weight: 0.1 },
    ],
    predicted_days_to_failure: 110,
    customers_affected_estimate: 900,
    sensor: { temperature_c: 41, vibration_mm_s: 0.5, oil_bdv_kv: 64, partial_discharge_pc: 24 },
    weather: { condition: 'Clear', wind_kmh: 22, humidity_pct: 50, rain_mm: 0 },
  },
  {
    asset_id: 'TX-630',
    location: { lat: 20.6, lon: 72.96, name: 'Valsad Substation 1', state: 'Gujarat', district: 'Valsad' },
    asset_type: 'transformer',
    risk_score: 0.25,
    risk_level: 'low',
    contributing_factors: [
      { factor: 'oil_quality', value: 'good', weight: 0.4 },
      { factor: 'vibration', value: 'nominal', weight: 0.3 },
      { factor: 'weather_forecast', value: 'monsoon_humidity', weight: 0.2 },
    ],
    predicted_days_to_failure: 130,
    customers_affected_estimate: 1100,
    sensor: { temperature_c: 39, vibration_mm_s: 0.4, oil_bdv_kv: 66, partial_discharge_pc: 20 },
    weather: { condition: 'Monsoon', wind_kmh: 28, humidity_pct: 82, rain_mm: 15 },
  },
  {
    asset_id: 'TX-740',
    location: { lat: 22.46, lon: 73.69, name: 'Panchmahal Substation', state: 'Gujarat', district: 'Panchmahal' },
    asset_type: 'transformer',
    risk_score: 0.29,
    risk_level: 'low',
    contributing_factors: [
      { factor: 'oil_quality', value: 'good', weight: 0.35 },
      { factor: 'age', value: '9_years', weight: 0.25 },
      { factor: 'weather_forecast', value: 'clear', weight: 0.1 },
    ],
    predicted_days_to_failure: 115,
    customers_affected_estimate: 1300,
    sensor: { temperature_c: 41, vibration_mm_s: 0.5, oil_bdv_kv: 63, partial_discharge_pc: 25 },
    weather: { condition: 'Clear', wind_kmh: 18, humidity_pct: 44, rain_mm: 0 },
  },
  {
    asset_id: 'TX-850',
    location: { lat: 22.68, lon: 74.22, name: 'Dahod Substation', state: 'Gujarat', district: 'Dahod' },
    asset_type: 'transformer',
    risk_score: 0.32,
    risk_level: 'low',
    contributing_factors: [
      { factor: 'oil_quality', value: 'good', weight: 0.35 },
      { factor: 'maintenance_overdue', value: 'none', weight: 0.1 },
      { factor: 'weather_forecast', value: 'clear', weight: 0.1 },
    ],
    predicted_days_to_failure: 105,
    customers_affected_estimate: 1050,
    sensor: { temperature_c: 42, vibration_mm_s: 0.5, oil_bdv_kv: 62, partial_discharge_pc: 26 },
    weather: { condition: 'Clear', wind_kmh: 16, humidity_pct: 46, rain_mm: 0 },
  },
  {
    asset_id: 'FD-960',
    location: { lat: 22.77, lon: 73.68, name: 'Kheda Feeder 2', state: 'Gujarat', district: 'Kheda' },
    asset_type: 'feeder',
    risk_score: 0.36,
    risk_level: 'low',
    contributing_factors: [
      { factor: 'load_overcurrent', value: 'nominal', weight: 0.3 },
      { factor: 'age', value: '10_years', weight: 0.25 },
      { factor: 'weather_forecast', value: 'clear', weight: 0.1 },
    ],
    predicted_days_to_failure: 98,
    customers_affected_estimate: 1400,
    sensor: { temperature_c: 43, vibration_mm_s: 0.6, oil_bdv_kv: 61, partial_discharge_pc: 30 },
    weather: { condition: 'Clear', wind_kmh: 20, humidity_pct: 50, rain_mm: 0 },
  },
  // ── Non-Gujarat assets (for India view / all-assets list) ────────────────────
  {
    asset_id: 'TX-231',
    location: { lat: 19.08, lon: 72.88, name: 'Mumbai Coastal Substation 2', state: 'Maharashtra' },
    asset_type: 'transformer',
    risk_score: 0.83,
    risk_level: 'high',
    contributing_factors: [
      { factor: 'weather_forecast', value: 'cyclone_watch', weight: 0.45 },
      { factor: 'corrosion', value: 'salt_exposure', weight: 0.3 },
      { factor: 'load_overcurrent', value: 'peak_exceeded', weight: 0.25 },
    ],
    predicted_days_to_failure: 8,
    customers_affected_estimate: 9200,
    sensor: { temperature_c: 80, vibration_mm_s: 3.5, oil_bdv_kv: 20, partial_discharge_pc: 310 },
    weather: { condition: 'Cyclone Watch', wind_kmh: 95, humidity_pct: 92, rain_mm: 45 },
  },
  {
    asset_id: 'TX-355',
    location: { lat: 28.61, lon: 77.21, name: 'Delhi Central Substation', state: 'Delhi' },
    asset_type: 'transformer',
    risk_score: 0.74,
    risk_level: 'high',
    contributing_factors: [
      { factor: 'load_overcurrent', value: 'sustained_peak', weight: 0.4 },
      { factor: 'weather_forecast', value: 'heat_wave', weight: 0.35 },
      { factor: 'maintenance_overdue', value: '30_days', weight: 0.25 },
    ],
    predicted_days_to_failure: 15,
    customers_affected_estimate: 11400,
    sensor: { temperature_c: 78, vibration_mm_s: 3.0, oil_bdv_kv: 26, partial_discharge_pc: 220 },
    weather: { condition: 'Heat Wave', wind_kmh: 35, humidity_pct: 28, rain_mm: 0 },
  },
  {
    asset_id: 'FD-402',
    location: { lat: 21.15, lon: 79.09, name: 'Nagpur Feeder 6', state: 'Maharashtra' },
    asset_type: 'feeder',
    risk_score: 0.44,
    risk_level: 'medium',
    contributing_factors: [
      { factor: 'age', value: '19_years', weight: 0.3 },
      { factor: 'load_overcurrent', value: 'moderate', weight: 0.4 },
      { factor: 'weather_forecast', value: 'clear', weight: 0.3 },
    ],
    predicted_days_to_failure: 52,
    customers_affected_estimate: 2900,
    sensor: { temperature_c: 52, vibration_mm_s: 1.1, oil_bdv_kv: 49, partial_discharge_pc: 70 },
    weather: { condition: 'Clear', wind_kmh: 22, humidity_pct: 48, rain_mm: 0 },
  },
  {
    asset_id: 'BR-478',
    location: { lat: 26.92, lon: 75.79, name: 'Jaipur Ring Breaker 1', state: 'Rajasthan' },
    asset_type: 'breaker',
    risk_score: 0.52,
    risk_level: 'medium',
    contributing_factors: [
      { factor: 'switch_cycle_count', value: 'moderate', weight: 0.3 },
      { factor: 'weather_forecast', value: 'dust_storm', weight: 0.4 },
      { factor: 'corrosion', value: 'minor', weight: 0.3 },
    ],
    predicted_days_to_failure: 40,
    customers_affected_estimate: 3600,
    sensor: { temperature_c: 58, vibration_mm_s: 1.3, oil_bdv_kv: 44, partial_discharge_pc: 90 },
    weather: { condition: 'Dust Storm', wind_kmh: 60, humidity_pct: 15, rain_mm: 0 },
  },
  {
    asset_id: 'PL-561',
    location: { lat: 26.85, lon: 80.95, name: 'Lucknow Pole Line 9', state: 'Uttar Pradesh' },
    asset_type: 'pole',
    risk_score: 0.66,
    risk_level: 'medium',
    contributing_factors: [
      { factor: 'wood_decay_index', value: 'moderate', weight: 0.35 },
      { factor: 'vegetation_contact_risk', value: 'elevated', weight: 0.35 },
      { factor: 'weather_forecast', value: 'monsoon_humidity', weight: 0.3 },
    ],
    predicted_days_to_failure: 22,
    customers_affected_estimate: 1850,
    sensor: { temperature_c: 64, vibration_mm_s: 1.7, oil_bdv_kv: 36, partial_discharge_pc: 138 },
    weather: { condition: 'Monsoon', wind_kmh: 44, humidity_pct: 86, rain_mm: 30 },
  },
  {
    asset_id: 'TX-609',
    location: { lat: 12.97, lon: 77.59, name: 'Bengaluru South Substation', state: 'Karnataka' },
    asset_type: 'transformer',
    risk_score: 0.19,
    risk_level: 'low',
    contributing_factors: [
      { factor: 'oil_quality', value: 'good', weight: 0.4 },
      { factor: 'vibration', value: 'nominal', weight: 0.3 },
      { factor: 'maintenance_overdue', value: 'none', weight: 0.1 },
    ],
    predicted_days_to_failure: 160,
    customers_affected_estimate: 6700,
    sensor: { temperature_c: 36, vibration_mm_s: 0.3, oil_bdv_kv: 70, partial_discharge_pc: 15 },
    weather: { condition: 'Clear', wind_kmh: 14, humidity_pct: 58, rain_mm: 0 },
  },
  {
    asset_id: 'TX-833',
    location: { lat: 22.57, lon: 88.36, name: 'Kolkata East Substation', state: 'West Bengal' },
    asset_type: 'transformer',
    risk_score: 0.68,
    risk_level: 'medium',
    contributing_factors: [
      { factor: 'weather_forecast', value: 'monsoon_flooding', weight: 0.4 },
      { factor: 'oil_quality', value: 'moderate', weight: 0.3 },
      { factor: 'age', value: '22_years', weight: 0.3 },
    ],
    predicted_days_to_failure: 20,
    customers_affected_estimate: 5600,
    sensor: { temperature_c: 66, vibration_mm_s: 1.9, oil_bdv_kv: 34, partial_discharge_pc: 148 },
    weather: { condition: 'Monsoon Flooding', wind_kmh: 50, humidity_pct: 94, rain_mm: 65 },
  },
  {
    asset_id: 'BR-905',
    location: { lat: 17.39, lon: 78.49, name: 'Hyderabad Ring Breaker 2', state: 'Telangana' },
    asset_type: 'breaker',
    risk_score: 0.15,
    risk_level: 'low',
    contributing_factors: [
      { factor: 'switch_cycle_count', value: 'low', weight: 0.3 },
      { factor: 'corrosion', value: 'none', weight: 0.3 },
      { factor: 'weather_forecast', value: 'clear', weight: 0.2 },
    ],
    predicted_days_to_failure: 210,
    customers_affected_estimate: 2100,
    sensor: { temperature_c: 34, vibration_mm_s: 0.3, oil_bdv_kv: 72, partial_discharge_pc: 12 },
    weather: { condition: 'Clear', wind_kmh: 12, humidity_pct: 52, rain_mm: 0 },
  },
];

const EXPLANATIONS = {
  'FD-268': 'Kutch Feeder 8 is at critical risk — sustained overload at 95%+ capacity during an active heat wave, with conductors aged 24 years. Immediate load-shedding and crew dispatch required.',
  'TX-104': 'Substation 4 is high priority because oil quality has degraded alongside rising vibration, with a storm forecast within 72 hours.',
  'TX-330': 'Rajkot Substation 2 has storm-force winds approaching within 72 hours while oil quality is degrading — risk of concurrent mechanical and weather failure.',
  'FD-221': 'Naranpura Feeder 2 is running sustained overcurrent on aging 28-year conductors, and a heat wave will keep peak load elevated through the week.',
  'TX-088': 'Surat East is high priority: routine maintenance is 46 days overdue, oil quality has softened, and a storm is approaching the coast within 72 hours.',
  'FD-146': 'Bharuch Feeder 1 is exceeding peak load capacity with elevated vegetation contact risk, and a storm is forecast within 72 hours.',
  'TX-501': 'Junagadh Substation 1 shows moderate oil degradation compounded by monsoon humidity — schedule maintenance before the next heavy rain cycle.',
  'BR-317': 'Ring Breaker 3 shows a high switch-cycle count and visible corrosion on contacts, compounded by incoming monsoon humidity.',
  'PL-542': 'Pole Line 5 is currently low risk — decay index and lean angle are both within spec and the forecast is clear.',
  'TX-019': 'Ahmedabad North is in good standing across oil quality, vibration, and maintenance history — no near-term action required.',
};

const PLAN_STEPS = {
  'FD-268': { priority_rank: 1, action: 'Immediate load-shedding on Kutch Feeder 8. Pre-position emergency repair crew at Bhuj depot before heat wave peak (next 8 hours).', eta_hours: 8 },
  'TX-104': { priority_rank: 2, action: 'Dispatch inspection crew within 24 hours; pre-position repair crew near Anand Substation 4 ahead of the forecasted storm.', eta_hours: 24 },
  'TX-330': { priority_rank: 3, action: 'Pre-stage mobile transformer at Rajkot depot. Initiate storm-prep protocol — secure all outdoor switchgear and cable terminations.', eta_hours: 32 },
  'FD-146': { priority_rank: 4, action: 'Schedule load-shedding review and vegetation clearance along Bharuch Feeder 1 before the storm front arrives.', eta_hours: 36 },
  'FD-221': { priority_rank: 5, action: 'Deploy thermal inspection to Naranpura Feeder 2 and prepare a temporary load-transfer plan for the heat wave peak.', eta_hours: 48 },
  'TX-088': { priority_rank: 6, action: 'Assign maintenance crew to clear the 46-day overdue service window at Surat East Substation before storm makes access difficult.', eta_hours: 60 },
  'BR-317': { priority_rank: 7, action: 'Queue contact cleaning and corrosion treatment for Ring Breaker 3 ahead of monsoon humidity onset.', eta_hours: 72 },
};

export function mockExplain(assetId) {
  const asset = MOCK_ASSETS.find((a) => a.asset_id === assetId);
  const plan_step = PLAN_STEPS[assetId] || {
    priority_rank: null,
    action: 'No immediate dispatch action required; continue routine monitoring.',
    eta_hours: null,
  };
  return {
    asset_id: assetId,
    explanation: EXPLANATIONS[assetId] || (asset ? `${asset.location.name} has a risk score of ${asset.risk_score}.` : 'No explanation available.'),
    plan_step,
  };
}

export function mockDispatchPlan() {
  return Object.keys(PLAN_STEPS)
    .map((assetId) => mockExplain(assetId))
    .sort((a, b) => a.plan_step.priority_rank - b.plan_step.priority_rank);
}

export function mockAsk(question) {
  const q = question.toLowerCase();
  const topAsset = [...MOCK_ASSETS].sort((a, b) => b.risk_score - a.risk_score)[0];
  if (q.includes('highest') || q.includes('top') || q.includes('worst')) {
    return `${topAsset.location.name} (${topAsset.asset_id}) is the highest-priority asset right now, with a risk score of ${topAsset.risk_score} and an estimated ${topAsset.predicted_days_to_failure} days to failure, affecting roughly ${topAsset.customers_affected_estimate.toLocaleString()} customers.`;
  }
  if (q.includes('storm') || q.includes('weather')) {
    const stormAssets = MOCK_ASSETS.filter((a) => a.contributing_factors.some((f) => String(f.value).includes('storm')));
    const names = stormAssets.map((a) => a.location.name).join(', ');
    return `Assets currently flagged against the incoming storm window: ${names}. Recommend pre-positioning repair crews near these sites within the next 24–48 hours.`;
  }
  if (q.includes('customer')) {
    const total = MOCK_ASSETS.reduce((sum, a) => sum + a.customers_affected_estimate, 0);
    return `Across all tracked assets, roughly ${total.toLocaleString()} customers fall within the estimated impact radius if no preventive action is taken.`;
  }
  return `Based on current telemetry, ${topAsset.location.name} remains the top concern (risk score ${topAsset.risk_score}). Ask me about a specific asset ID, the storm-exposed sites, or total customer impact for more detail.`;
}
